package Inmobilaria.GyL.Enums;

public enum Type {
//    HOUSE,APARTMENT,CABIN,DUPLEX,TRIPLEX,PH,GARAGE,WAREHOUSE
    CASA,DEPARTAMENTO,CABAÑA,DUPLEX,TRIPLEX,PH,COCHERA,DEPOSITO,CHALET,PISO,TERRENO,OFICINA,LOTE,COMERCIO,CAMPO;
}
